/*
 * (c) Copyright 2022 ~ Trust Nexus, Inc.
 * All technologies described here in are "Patent Pending".
 * License information:  http://www.trustnexus.io/license.htm
 *
 * AS LONG AS THIS NOTICE IS MAINTAINED THE LICENSE PERMITS REDISTRIBUTION OR RE-POSTING
 * OF THIS SOURCE CODE TO A PUBLIC REPOSITORY (WITH OR WITHOUT MODIFICATIONS)!
 *
 * Report License Violations:  trustnexus.io@austin.rr.com
 */

package io.trustnexus.webauthnplusb.util;

public class Constants {

    public static final String DOMAIN_NAME_VALUE = "www.tnxsecure.com";

    /*
     * Organizations running the WebAuthn+ Web Application and providing their own version of the TNX WebAuthn+ mobile app
     * should replace this public key and its UUID with the value generated by running
     * io.trustnexus.util.InitializeB_Keys
     *
     * As long as the mobile app is distributed in a secure process, providing the public key within the app and securing
     * the private key on your server should work fine.
     *
     * In this prototype application we are going to store our private keys in the data base.
     * This is NOT a good idea for a production level application.
     * Some good suggestions can be found here:
     * https://security.stackexchange.com/questions/12332/where-to-store-a-server-side-encryption-key
     *
     * If the keys for the MOBILE_APP_PROVIDER_KEY_OWNER are ever compromised new keys will need to be issued by
     * creating a new version of the WebAuthn+ Secure Mobile application and requiring all users to upgrade.
     *
     * The utility program InitializeB_Keys.java, run from Eclipse, should have populated the database table publicprivatekey.
     * Copy the publicKeyHex value and uuid value into the constants below.
     */
    public static final String MOBILE_APP_PROVIDER_PUBLIC_KEY = "30820222300D06092A864886F70D01010105000382020F003082020A0282020100DFA68DA96608E0" +
            "C07805C91C0C5200BE4D242DCBC040B999B5886854D765A1F035B499328A58DD1C28636E21BE90F707C83D7257AB693C6791720D6AFB4CE310470A89BEF9CA50DFD4C" +
            "D622748BBB414C82333E468124A4C91800809314322D9350CDCCF7F08CCCAF3DDF77529F3F560B1F46E695E36E1CFD8919662700C4BC749FD6A911746791D5948709C" +
            "A48A03DBF8411F96165856FB07394D8CF1222CB5E9AD9BDFE9B43BB292712640B3B262F9804B8D7805ABBCA4C5F07BE7A4E82CF9C2E2E54D96E0FCBD974763822F535C" +
            "8EC338ADAF499CFD0293674735AD694C65C16CB88822FB2F961C4C4DBC944A9C6413A54B161C11631ADCCF38F94729034C4217EAC73E226B730C5157D28568C55D082" +
            "5DAA9F4748C759B235F6A6ABED8D4AB2E854473F233FEE668ECFEDD5BB9B84B8C0F4D6F308B79886109E02780F38BAC7C2E1646DD6543CFA56292DD3FB1E8C0F7BC81" +
            "C3C13B95F73C4F1D648C9EED1267AA51C7E715F5C893F844D782DCB7F1B8FA7422B0F99FB428E74E1D5C4C4858185E0F18F11AAA0CC70EEC6F8A5B6131B56001DBA5" +
            "D490DF31020EBF9EC3F0E8899F08B3FDF4BA2774CAE2B269EBEF86FC1D0ACAE739D12A7C8BB6A19B21124023D304800114F0C8AB666358C5BD5688466BCEB25CF69D3" +
            "8FBE77BFB364AFC2008920CBAAD7F57997050539BA6C489F82FBFD0FC031A8B02A465E4890A4FFD0203010001";

    public static final String MOBILE_APP_PROVIDER_PUBLIC_KEY_UUID = "1653115662393-4284C11E-BD60-4A01-9451-F8EF3D280F8F";

    public static final String DEFAULT_FINANCIAL_CREDENTIAL_TYPE = "com.cwbank.credentialtype.Financial_Test_1";

    public static final String FUNDS_SENT = "FUNDS SENT ";
    public static final String SMS_BASE_URL = "http://www.webauthnplus.com/foundation/funds.action?";
    public static final String SENDER = "sender";
    public static final String REFERENCE = "ref";

    // ------------------------------------------------------------------------------------------------------------------

    static final String ZULU_ADJUSTMENT = "Z-6";

    //  No "I" or "O" which eliminates numerical confusion.
    static final char[] CHARACTER_ARRAY = {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'J', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'};

    static final String[] SENSITIVE_WORDS_FOUR = {"ABBO", "ALLA", "ANAL", "ANUS", "ARAB", "ARSE", "BANG", "BARF", "BAST", "BLOW", "BOMB",
            "BOMD", "BOOB", "BOOM", "BUNG", "BUTT", "CHAV", "CHIN", "CIGG", "CIGS", "CLIT", "COCK", "COHE", "COON", "CRAP", "CUMM", "CUNN",
            "CUNT", "DAGO", "DAMN", "DEAD", "DEGO", "DETH", "DIED", "DIES", "DIKE", "DINK", "DONG", "DOOM", "DOPE", "DRUG", "DUMB", "DYKE",
            "EVIL", "FAGG", "FART", "FEAR", "FIRE", "FLOO", "FORE", "FUCK", "FUKS", "GOOK", "GOYM", "GUNN", "GYPO", "GYPP", "HEBE", "HEEB",
            "HELL", "HOBO", "HOES", "HOLE", "HOMO", "HORE", "HORK", "ITCH", "JIGA", "JISM", "JIZM", "JIZZ", "JUGS", "KIKE", "KILL", "KINK",
            "KOON", "KRAP", "KUNT", "KYKE", "LEZZ", "LIES", "LIMY", "METH", "MILF", "MOFO", "MOKY", "MUFF", "MUNT", "NAZI", "NIGG", "NIGR",
            "NUDE", "NUKE", "ORAL", "ORGA", "ORGY", "PAKI", "PAYO", "PERV", "PHUK", "PHUQ", "PIMP", "PISS", "PIXY", "POHM", "POON", "POOP",
            "PORN", "PRIC", "PUBE", "PUDD", "PUKE", "PUSS", "PUSY", "QUIM", "RAPE", "RUMP", "SATN", "SCAG", "SCAT", "SCUM", "SEXX", "SEXY",
            "SHAG", "SHAT", "SHAV", "SHIT", "SICK", "SKUM", "SLAV", "SLUT", "SMUT", "SNOT", "SPIC", "SPIG", "SPIK", "SPIT", "SUCC", "SUCK",
            "TAFF", "TANG", "TARD", "TEAT", "TITT", "TITS", "TITY", "TURD", "TWAT", "VIBR", "WANK", "WHIT", "WHIZ", "WHOP", "WHOR", "WUSS",
            "XXXX"};

    static final String[] SENSITIVE_WORDS_THREE = {"ALA", "CUM", "FAG", "FUC", "GOD", "JAP", "JIZ", "KIL", "LIE", "LDS", "LSD", "NIG", "PIS", "PEE",
            "PUD", "PUS", "SEX", "SAD", "SIC", "SUC", "SUX", "TIT", "WIZ", "XXX"};

    // ------------------------------------------------------------------------------------------------------------------

    /*
     * Strings that are not visible to the user are stored here.
     *
     * Most of these strings are keys or messages that are shared with the TNX Web Application.
     */

    public static final int TNX_NOTIFICATION = 888;
    public static final String LOG_PREFIX = "TNX";
    public static final long MAX_IDLE_TIME = 1000 * 60 * 10;

    public static final int PASSWORD_VERIFICATION_FAILED = 1;
    public static final int INCOMPLETE_PROFILE = 2;
    public static final int MAX_IDLE_TIME_EXCEEDED = 3;
    public static final int INSUFFICIENT_CONTACT_INFORMATION = 4;

    /* TODO: RESET URL_BASE to the URL of your Web Application. */
    private static final String URL_BASE = "https://www.webauthnplus.com/foundation/";

    public static final String CREATE_USER_URL = URL_BASE + "createUser.action";
    public static final String CREATE_SECURITY_KEY_URL = URL_BASE + "createSecurityKey.action";
    public static final String UPDATE_USER_URL = URL_BASE + "updateUser.action";
    public static final String CREATE_USER_PUBLIC_KEY_URL = URL_BASE + "createUserPublicKey.action";
    public static final String MOBILE_APPLICATION_SIGN_ON_URL = URL_BASE + "mobileApplicationSignOn.action";
    public static final String RETRIEVE_CREDENTIAL_META_DATA_URL = URL_BASE + "retrieveCredentialMetaData.action";
    public static final String CANCEL_CREATE_CREDENTIAL_URL = URL_BASE + "cancelCreateCredential.action";
    public static final String RETRIEVE_MOBILE_APP_PROVIDER_TRANSACTION_UUID_URL = URL_BASE + "retrieveTransactionUuid.action";
    public static final String UPDATE_FIREBASE_DEVICE_ID_URL = URL_BASE + "updateFirebaseDeviceId.action";
    public static final String TEST_CREDENTIAL_PROVIDER = "IVY Bank";

    static final String OBFUSCATED_IDENTIFIER = "obfuscatedIdentifier";
    public static final String SCREEN_NAME = "screenName";
    public static final String EMAIL = "email";
    public static final String USER_UUID = "userUuid";
    public static final String FIRST_NAME = "firstName";
    public static final String LAST_NAME = "lastName";
    public static final String PHONE = "phone";
    public static final String FIRE_BASE_DEVICE_ID = "firebaseDeviceId";

    public static final String ADDRESS_TYPE = "addressType";

    public static final String LEGAL_ADDRESS_LINE_ONE = "legalAddressLineOne";
    public static final String LEGAL_ADDRESS_LINE_TWO = "legalAddressLineTwo";
    public static final String LEGAL_ADDRESS_CITY = "legalAddressCity";
    public static final String LEGAL_ADDRESS_STATE = "legalAddressState";
    public static final String LEGAL_ADDRESS_POSTAL_CODE = "legalAddressPostalCode";
    public static final String LEGAL_ADDRESS_COUNTRY = "legalAddressCountry";

    public static final String MAILING_ADDRESS_LINE_ONE = "mailingAddressLineOne";
    public static final String MAILING_ADDRESS_LINE_TWO = "mailingAddressLineTwo";
    public static final String MAILING_ADDRESS_CITY = "mailingAddressCity";
    public static final String MAILING_ADDRESS_STATE = "mailingAddressState";
    public static final String MAILING_ADDRESS_POSTAL_CODE = "mailingAddressPostalCode";
    public static final String MAILING_ADDRESS_COUNTRY = "legalAddressCountry";

    public static final String ORGANIZATION_ADDRESS_LINE_ONE = "organizationAddressLineOne";
    public static final String ORGANIZATION_ADDRESS_LINE_TWO = "organizationAddressLineTwo";
    public static final String ORGANIZATION_ADDRESS_CITY = "organizationAddressCity";
    public static final String ORGANIZATION_ADDRESS_STATE = "organizationAddressState";
    public static final String ORGANIZATION_ADDRESS_POSTAL_CODE = "organizationAddressPostalCode";
    public static final String ORGANIZATION_ADDRESS_COUNTRY = "organizationAddressCountry";

    public static final String ORGANIZATION_NAME = "organizationName";
    public static final String ORGANIZATION_URL = "organizationUrl";
    public static final String ORGANIZATION_TITLE = "organizationTitle";
    public static final String ORGANIZATION_PHONE = "organizationPhone";

    public static final String CREDENTIAL_PROVIDER_NAME = "credentialProviderName";
    public static final String CREDENTIAL_PROVIDER_UUID = "credentialProviderUuid";
    public static final String CREDENTIAL_PROVIDER_LOADED = "Credential provider loaded.";
    public static final String CREDENTIAL_ICON_DOWN_LOADED = "Credential icon downoaded.";

    public static final String FIREBASE_MSG_TYPE_KEY = "firebaseMsgTypeKey";
    public static final String FIREBASE_MSG_TYPE_CREATE_CREDENTIAL = "createCredential";
    public static final String FIREBASE_MSG_TYPE_SIGN_ON = "signOn";
    public static final String FIREBASE_MSG_TYPE_CONFIRM_FUNDS_TRANSFER = "confirmFundsTransfer";
    public static final String FIREBASE_MSG_TYPE_SIGN_DISTRIBUTED_LEDGER = "signDistributedLedger";

    public static final String SESSION_UUID = "sessionUuid";
    public static final String SESSION_UUID_SIGNED = "sessionUuidSigned";
    public static final String DOMAIN_NAME = "domainName";
    public static final String CREATE_CREDENTIAL_URL = "createCredentialUrl";
    public static final String DELETE_CREDENTIAL_URL = "deleteCredentialUrl";
    public static final String SIGN_ON_URL = "signOnUrl";
    public static final String CANCEL_SIGN_ON_URL = "cancelSignOnUrl";
    public static final String RETRIEVE_UNSIGNED_DISTRIBUTED_LEDGER_URL = "retrieveUnsignedDistributedLedgerUrl";
    public static final String RETURN_SIGNED_DISTRIBUTED_LEDGER_URL = "returnSignedDistributedLedgerUrl";
    public static final String RETRIEVE_TRANSACTION_UUID_URL = "retrieveTransactionUuidUrl";
    public static final String PUBLIC_KEY_UUID = "publicKeyUuid";
    public static final String CREDENTIAL_ICON_URL = "credentialIconUrl";
    public static final String CREDENTIAL_TYPE = "credentialType";
    public static final String CREDENTIAL_DISPLAY_NAME = "credentialDisplayName";
    public static final String CREDENTIAL_UUID = "credentialUuid";
    public static final String DISTRIBUTED_LEDGER_DOWNLOADED = "distributedLedgerDownloaded";
    public static final String DISTRIBUTED_LEDGER_UPLOADED = "distributedLedgerUploaded";
    public static final String DISTRIBUTED_LEDGER = "distributedLedger";
    public static final String DISTRIBUTED_LEDGER_SIGNED = "distributedLedgerSigned";
    public static final String DISTRIBUTED_LEDGER_HASH = "distributedLedgerHash";
    public static final String DISTRIBUTED_LEDGER_SIGNED_HASH = "distributedLedgerSignedHash";
    public static final String SIGNATURE_SUCCESSFUL = "Signature Successful";

    public static final String SERVICE_UUID = "serviceUuid";
    public static final String AUTHENTICATION_CODE = "authenticationCode";
    public static final String VERIFICATION_CODE = "verificationCode";

    static final String PUBLIC_KEY_UUID_LABEL = "publicKeyUuid";
    static final String TRANSFER_KEY_ENCRYPTED_HEX = "transferKeyEncryptedHex";
    public static final String SECRET_KEY = "secretKey";
    public static final String TRANSFER_DATA_ENCRYPTED_HEX = "transferDataEncryptedHex";
    public static final String TRANSFER_DATA_ENCRYPTED_HASHED_HEX = "transferDataEncryptedHashedHex";  // TODO:  rename to TRANSFER_DATA_MAC
    public static final String USER_SECURITY_KEY_ENCRYPTED = "userSecurityKeyEncrypted";
    public static final String PUBLIC_KEY_HEX = "publicKeyHex";
    public static final String TRANSACTION_UUID = "transactionUuid";
    public static final String TRANSACTION_UUID_SIGNED = "transactionUuidSigned";

    public static final String USER_SUCCESSFULLY_CREATED = "User successfully created.";
    public static final String PUBLIC_KEY_SAVED = "Public key successfully saved.";
    public static final String PROFILE_UPDATED = "Profile updated.";
    public static final String SIGN_ON_SUCCESSFUL = "Sign On Successful.";
    public static final String SECURITY_KEY_CREATED = "Security key created.";
    public static final String FIRE_BASE_DEVICE_ID_UPDATED = "Firebase device ID successfully updated.";

    public static final String FUNDS_TRANSFER = ", is attempting to send funds to your account.  Please click on the follwoing link.";
    public static final String JSON_FUNDS_TRANSFER = "jsonFundsTransfer";
    public static final String FUNDS_TRANSFER_UUID = "fundsTransferUuid";
    public static final String FUNDS_TRANSFER_INITIALIZED = "Funds transfer initialized.";

    public static final String TIMESTAMP = "timestamp";
    public static final String SENDER_DATA = "senderData";
    public static final String SENDER_NAME = "senderName";
    public static final String SENDER_PHONE_NUMBER = "senderPhoneNumber";
    public static final String SENDER_EMAIL = "senderEmail";

    public static final String RECIPIENT_DATA = "recipientData";
    public static final String RECIPIENT_NAME = "recipientName";
    public static final String RECIPIENT_PHONE_NUMBER = "recipientPhoneNumber";
    public static final String RECIPIENT_EMAIL = "recipientEmail";
    public static final String TRANSFER_AMOUNT = "transferAmount";

    public static final String SENDER_SIGNATURE_ALGORITHM = "senderSignatureAlgorithm";
    public static final String SENDER_SECURE_HASH_ALGORITHM = "senderSecureHashAlgorithm";
    public static final String SENDER_HASH = "senderHash";
    public static final String SENDER_SIGNED_HASH = "senderSignedHash";

    public static final String RECIPIENT_SIGNATURE_ALGORITHM = "recipientSignatureAlgorithm";
    public static final String RECIPIENT_SECURE_HASH_ALGORITHM = "recipientSecureHashAlgorithm";
    public static final String RECIPIENT_HASH = "recipientHash";
    public static final String RECIPIENT_SIGNED_HASH = "recipientSignedHash";

    public static final String SENDING_BANK_NAME = "sendingBankName";
    public static final String TEST_CHANGE_GIT_HUB = "test change";
}
