package io.trustnexus.webauthnplus.util;

public class Constants {

  public static final String DOMAIN_NAME_VALUE = "www.tnxsecure.com";

  /*
   * Organizations running the TNX Web Application and providing their own version of the TNX WebAuthn+ mobile app
   * should replace this public key and its UUID with the value generated by running
   * io.trustnexus.util.InitializeB_Keys
   *
   * As long as the mobile app is distributed in a secure process, providing the public key within the app and securing
   * the private key on your server should work fine.
   */
  public static final String MOBILE_APP_PROVIDER_PUBLIC_KEY = "30820222300D06092A864886F70D01010105000382020F003082020A0282020100C0B0E648866A26FE08ADE6B335A355" +
          "70384DC5F24DDCD9A82E0AED54CAD55304A3F69E061994081199B4FBB8C3ED76C5945E6C79BBF0BBFB89C2549BF233A8DCD9C535FE8802340256118F3BAADE65CF8CE49B96FD128EF8F8" +
          "330B96CA97BC156A80BC55699AD4347C5B4336BD1ACCD637AA813E3BFFFD46E8F0B256B76A4203E5780C9038B856713F1B44286C766AD96AB87012CAE53431E04EA81C4C2C5A6A6E98E6" +
          "F7D6E4DF52E57A664B1DD5E2AEC9E757386204828D36467E43BB81070B9705C59057C2B77243073AC1DC675966AAD073E099766B09D474DA36EDD8E4DD07DE3045818CE04D3782938109" +
          "64EDEB892641EE1ADA295B05A9F0DF1031C30EA02096BA2EF046E1BA17483924694411364262CD85F8E3E45BBCE8BDD18DD8101E2A3DD8C1188FE05D3AF7158BC6EE911B0E5C491A33EF" +
          "F8EAC5AF8480D8CBD2A5CFE1ADF1ADF16E46247E9DE566BFF393E52D4D12DC70E1129315FC1E36114AC774664C7FD45E207F7822F2FD10CE0F27CCCC940A837E833B52823AD4E448120D" +
          "AE1AB5D73D99FB3F17304417FDEAA2CCE0C69BB92307FBBABEEC8E2A98415BE3126658C35E7D901532E6CF2F46202F5587AEBD734A0AE2B3D230B21C3CE01B13631C78DF97E718449BBF" +
          "76D4BAF0CFB91C547D99F8D1AED0A2D230836F3D639205E870DFEA4511598D191922EEB53AF99681A1D00A12EC3E74AAF3E6D7A3B30203010001";

  public static final String MOBILE_APP_PROVIDER_PUBLIC_KEY_UUID = "1620483590224-C68FBF87-6447-41A4-9F5B-D7F725774224";

  public static final String DEFAULT_FINANCIAL_CREDENTIAL_TYPE = "com.cwbank.credentialtype.Financial_Test_1";

  public static final String FUNDS_SENT = "FUNDS SENT ";
  public static final String SMS_BASE_URL = "http://www.webauthnplus.com/foundation/funds.action?";
  public static final String SENDER = "sender";
  public static final String REFERENCE = "ref";

  // ------------------------------------------------------------------------------------------------------------------

  static final String ZULU_ADJUSTMENT = "Z-6";

  //  No "I" or "O" which eliminates numerical confusion.
  static final char[] CHARACTER_ARRAY = { 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'J', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z' };

  static final String[] SENSITIVE_WORDS_FOUR = {"ABBO", "ALLA", "ANAL", "ANUS", "ARAB", "ARSE", "BANG", "BARF", "BAST", "BLOW", "BOMB",
        "BOMD", "BOOB", "BOOM", "BUNG", "BUTT", "CHAV", "CHIN", "CIGG", "CIGS", "CLIT", "COCK", "COHE", "COON", "CRAP", "CUMM", "CUNN",
        "CUNT", "DAGO", "DAMN", "DEAD", "DEGO", "DETH", "DIED", "DIES", "DIKE", "DINK", "DONG", "DOOM", "DOPE", "DRUG", "DUMB", "DYKE",
        "EVIL", "FAGG", "FART", "FEAR", "FIRE", "FLOO", "FORE", "FUCK", "FUKS", "GOOK", "GOYM", "GUNN", "GYPO", "GYPP", "HEBE", "HEEB",
        "HELL", "HOBO", "HOES", "HOLE", "HOMO", "HORE", "HORK", "ITCH", "JIGA", "JISM", "JIZM", "JIZZ", "JUGS", "KIKE", "KILL", "KINK",
        "KOON", "KRAP", "KUNT", "KYKE", "LEZZ", "LIES", "LIMY", "METH", "MILF", "MOFO", "MOKY", "MUFF", "MUNT", "NAZI", "NIGG", "NIGR",
        "NUDE", "NUKE", "ORAL", "ORGA", "ORGY", "PAKI", "PAYO", "PERV", "PHUK", "PHUQ", "PIMP", "PISS", "PIXY", "POHM", "POON", "POOP",
        "PORN", "PRIC", "PUBE", "PUDD", "PUKE", "PUSS", "PUSY", "QUIM", "RAPE", "RUMP", "SATN", "SCAG", "SCAT", "SCUM", "SEXX", "SEXY",
        "SHAG", "SHAT", "SHAV", "SHIT", "SICK", "SKUM", "SLAV", "SLUT", "SMUT", "SNOT", "SPIC", "SPIG", "SPIK", "SPIT", "SUCC", "SUCK",
        "TAFF", "TANG", "TARD", "TEAT", "TITT", "TITS", "TITY", "TURD", "TWAT", "VIBR", "WANK", "WHIT", "WHIZ", "WHOP", "WHOR", "WUSS",
        "XXXX"};

  static final String[] SENSITIVE_WORDS_THREE = {"ALA", "CUM", "FAG", "FUC", "GOD", "JAP", "JIZ", "KIL", "LIE", "LDS", "LSD", "NIG", "PIS", "PEE",
          "PUD", "PUS", "SEX", "SAD", "SIC", "SUC", "SUX", "TIT", "WIZ", "XXX"};

  // ------------------------------------------------------------------------------------------------------------------

  /*
   * Strings that are not visible to the user are stored here.
   *
   * Most of these strings are keys or messages that are shared with the TNX Web Application.
   */

  public static final int TNX_NOTIFICATION = 888;
  public static final String LOG_PREFIX = "TNX";
  public static final long MAX_IDLE_TIME = 1000 * 60 * 10;

  public static final int PASSWORD_VERIFICATION_FAILED = 1;
  public static final int INCOMPLETE_PROFILE = 2;
  public static final int MAX_IDLE_TIME_EXCEEDED = 3;
  public static final int INSUFFICIENT_CONTACT_INFORMATION = 4;

  /* TODO: RESET URL_BASE to the URL of your Web Application. */
  private static final String URL_BASE = "https://www.webauthnplus.com/foundation/";

  public static final String CREATE_USER_URL = URL_BASE + "createUser.action";
  public static final String CREATE_SECURITY_KEY_URL = URL_BASE + "createSecurityKey.action";
  public static final String UPDATE_USER_URL = URL_BASE + "updateUser.action";
  public static final String CREATE_USER_PUBLIC_KEY_URL = URL_BASE + "createUserPublicKey.action";
  public static final String MOBILE_APPLICATION_SIGN_ON_URL = URL_BASE + "mobileApplicationSignOn.action";
  public static final String RETRIEVE_CREDENTIAL_META_DATA_URL = URL_BASE + "retrieveCredentialMetaData.action";
  public static final String CANCEL_CREATE_CREDENTIAL_URL = URL_BASE + "cancelCreateCredential.action";
  public static final String RETRIEVE_MOBILE_APP_PROVIDER_TRANSACTION_UUID_URL = URL_BASE + "retrieveTransactionUuid.action";
  public static final String UPDATE_FIREBASE_DEVICE_ID_URL = URL_BASE + "updateFirebaseDeviceId.action";
  public static final String TEST_CREDENTIAL_PROVIDER = "IVY Bank";

  static final String OBFUSCATED_IDENTIFIER = "obfuscatedIdentifier";
  public static final String SCREEN_NAME = "screenName";
  public static final String EMAIL = "email";
  public static final String USER_UUID = "userUuid";
  public static final String FIRST_NAME = "firstName";
  public static final String LAST_NAME = "lastName";
  public static final String PHONE = "phone";
  public static final String FIRE_BASE_DEVICE_ID = "firebaseDeviceId";

  public static final String ADDRESS_TYPE = "addressType";

  public static final String LEGAL_ADDRESS_LINE_ONE = "legalAddressLineOne";
  public static final String LEGAL_ADDRESS_LINE_TWO = "legalAddressLineTwo";
  public static final String LEGAL_ADDRESS_CITY = "legalAddressCity";
  public static final String LEGAL_ADDRESS_STATE = "legalAddressState";
  public static final String LEGAL_ADDRESS_POSTAL_CODE = "legalAddressPostalCode";
  public static final String LEGAL_ADDRESS_COUNTRY = "legalAddressCountry";

  public static final String MAILING_ADDRESS_LINE_ONE = "mailingAddressLineOne";
  public static final String MAILING_ADDRESS_LINE_TWO = "mailingAddressLineTwo";
  public static final String MAILING_ADDRESS_CITY = "mailingAddressCity";
  public static final String MAILING_ADDRESS_STATE = "mailingAddressState";
  public static final String MAILING_ADDRESS_POSTAL_CODE = "mailingAddressPostalCode";
  public static final String MAILING_ADDRESS_COUNTRY = "legalAddressCountry";

  public static final String ORGANIZATION_ADDRESS_LINE_ONE = "organizationAddressLineOne";
  public static final String ORGANIZATION_ADDRESS_LINE_TWO = "organizationAddressLineTwo";
  public static final String ORGANIZATION_ADDRESS_CITY = "organizationAddressCity";
  public static final String ORGANIZATION_ADDRESS_STATE = "organizationAddressState";
  public static final String ORGANIZATION_ADDRESS_POSTAL_CODE = "organizationAddressPostalCode";
  public static final String ORGANIZATION_ADDRESS_COUNTRY = "organizationAddressCountry";

  public static final String ORGANIZATION_NAME = "organizationName";
  public static final String ORGANIZATION_URL = "organizationUrl";
  public static final String ORGANIZATION_TITLE = "organizationTitle";
  public static final String ORGANIZATION_PHONE = "organizationPhone";

  public static final String CREDENTIAL_PROVIDER_NAME = "credentialProviderName";
  public static final String CREDENTIAL_PROVIDER_UUID = "credentialProviderUuid";
  public static final String CREDENTIAL_PROVIDER_LOADED = "Credential provider loaded.";
  public static final String CREDENTIAL_ICON_DOWN_LOADED = "Credential icon downoaded.";

  public static final String FIREBASE_MSG_TYPE_KEY = "firebaseMsgTypeKey";
  public static final String FIREBASE_MSG_TYPE_CREATE_CREDENTIAL = "createCredential";
  public static final String FIREBASE_MSG_TYPE_SIGN_ON = "signOn";
  public static final String FIREBASE_MSG_TYPE_CONFIRM_FUNDS_TRANSFER = "confirmFundsTransfer";
  public static final String FIREBASE_MSG_TYPE_SIGN_DISTRIBUTED_LEDGER = "signDistributedLedger";

  public static final String SESSION_UUID = "sessionUuid";
  public static final String SESSION_UUID_SIGNED = "sessionUuidSigned";
  public static final String DOMAIN_NAME = "domainName";
  public static final String CREATE_CREDENTIAL_URL = "createCredentialUrl";
  public static final String DELETE_CREDENTIAL_URL = "deleteCredentialUrl";
  public static final String SIGN_ON_URL = "signOnUrl";
  public static final String CANCEL_SIGN_ON_URL = "cancelSignOnUrl";
  public static final String RETRIEVE_UNSIGNED_DISTRIBUTED_LEDGER_URL = "retrieveUnsignedDistributedLedgerUrl";
  public static final String RETURN_SIGNED_DISTRIBUTED_LEDGER_URL = "returnSignedDistributedLedgerUrl";
  public static final String RETRIEVE_TRANSACTION_UUID_URL = "retrieveTransactionUuidUrl";
  public static final String PUBLIC_KEY_UUID = "publicKeyUuid";
  public static final String CREDENTIAL_ICON_URL = "credentialIconUrl";
  public static final String CREDENTIAL_TYPE = "credentialType";
  public static final String CREDENTIAL_DISPLAY_NAME = "credentialDisplayName";
  public static final String CREDENTIAL_UUID = "credentialUuid";
  public static final String DISTRIBUTED_LEDGER_DOWNLOADED = "distributedLedgerDownloaded";
  public static final String DISTRIBUTED_LEDGER_UPLOADED = "distributedLedgerUploaded";
  public static final String DISTRIBUTED_LEDGER = "distributedLedger";
  public static final String DISTRIBUTED_LEDGER_SIGNED = "distributedLedgerSigned";
  public static final String DISTRIBUTED_LEDGER_HASH = "distributedLedgerHash";
  public static final String DISTRIBUTED_LEDGER_SIGNED_HASH = "distributedLedgerSignedHash";
  public static final String SIGNATURE_SUCCESSFUL = "Signature Successful";

  public static final String AUTHENTICATION_CODE = "authenticationCode";
  public static final String VERIFICATION_CODE = "verificationCode";

  static final String PUBLIC_KEY_UUID_LABEL = "publicKeyUuid";
  static final String TRANSFER_KEY_ENCRYPTED_HEX = "transferKeyEncryptedHex";
  public static final String SECRET_KEY = "secretKey";
  public static final String TRANSFER_DATA_ENCRYPTED_HEX = "transferDataEncryptedHex";
  public static final String TRANSFER_DATA_ENCRYPTED_HASHED_HEX = "transferDataEncryptedHashedHex";  // TODO:  rename to TRANSFER_DATA_MAC
  public static final String USER_SECURITY_KEY_ENCRYPTED = "userSecurityKeyEncrypted";
  public static final String PUBLIC_KEY_HEX = "publicKeyHex";
  public static final String TRANSACTION_UUID = "transactionUuid";
  public static final String TRANSACTION_UUID_SIGNED = "transactionUuidSigned";

  public static final String USER_SUCCESSFULLY_CREATED = "User successfully created.";
  public static final String PUBLIC_KEY_SAVED = "Public key successfully saved.";
  public static final String PROFILE_UPDATED = "Profile updated.";
  public static final String SIGN_ON_SUCCESSFUL = "Sign On Successful.";
  public static final String SECURITY_KEY_CREATED = "Security key created.";
  public static final String FIRE_BASE_DEVICE_ID_UPDATED = "Firebase device ID successfully updated.";

  public static final String FUNDS_TRANSFER = ", is attempting to send funds to your account.  Please click on the follwoing link.";
  public static final String JSON_FUNDS_TRANSFER = "jsonFundsTransfer";
  public static final String FUNDS_TRANSFER_UUID = "fundsTransferUuid";
  public static final String FUNDS_TRANSFER_INITIALIZED = "Funds transfer initialized.";

  public static final String TIMESTAMP = "timestamp";
  public static final String SENDER_DATA = "senderData";
  public static final String SENDER_NAME = "senderName";
  public static final String SENDER_PHONE_NUMBER = "senderPhoneNumber";
  public static final String SENDER_EMAIL = "senderEmail";

  public static final String RECIPIENT_DATA = "recipientData";
  public static final String RECIPIENT_NAME = "recipientName";
  public static final String RECIPIENT_PHONE_NUMBER = "recipientPhoneNumber";
  public static final String RECIPIENT_EMAIL = "recipientEmail";
  public static final String TRANSFER_AMOUNT = "transferAmount";

  public static final String SENDER_SIGNATURE_ALGORITHM = "senderSignatureAlgorithm";
  public static final String SENDER_SECURE_HASH_ALGORITHM = "senderSecureHashAlgorithm";
  public static final String SENDER_HASH = "senderHash";
  public static final String SENDER_SIGNED_HASH = "senderSignedHash";

  public static final String RECIPIENT_SIGNATURE_ALGORITHM = "recipientSignatureAlgorithm";
  public static final String RECIPIENT_SECURE_HASH_ALGORITHM = "recipientSecureHashAlgorithm";
  public static final String RECIPIENT_HASH = "recipientHash";
  public static final String RECIPIENT_SIGNED_HASH = "recipientSignedHash";

  public static final String SENDING_BANK_NAME = "sendingBankName";
}
